name: End-to-End Test Suite

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '21'
    - run: npm install
    - run: npx playwright install 
    - run: npm run test
