name: AuroraFlow CI Test Suite

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Clone AuroraFlow repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Cache node_modules
      uses: actions/cache@v3
      id: cache-node-modules
      with:
        path: node_modules
        key: modules-${{ hashFiles('package-lock.json') }}

    - name: Cache Playwright binaries
      uses: actions/cache@v3
      id: playwright-cache
      with:
        path: ~/.cache/ms-playwright
        key: playwright-${{ hashFiles('package-lock.json') }}
    
    - name: Install AuroraFlow dependencies
      run: npm ci
    - run: npx playwright install --with-deps chrome chromium firefox webkit msedge
      if: steps.playwright-cache.outputs.cache-hit != 'true'
    - run: npx playwright install-deps
      if: steps.playwright-cache.outputs.cache-hit != 'true'
    
    - name: Run tests
      run: npm run test

    - name: Upload test Artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-test-results
        path: test-results/
